stages:
  - prepare
  - test
  - cleanup

build-container:
  stage: prepare
  script:
    - podman build -t sle-bci-init-ansible -f molecule/Dockerfile . 
    - podman images
  tags:
    - shell

pip install:
  stage: test
  script:
    - podman images
    - python3 -m virtualenv molecule_ansible && source molecule_ansible/bin/activate
    - source molecule_ansible/bin/activate && pip3 install ansible lxml testinfra molecule podman python-vagrant ansible-lint flake8 molecule[lint] molecule[podman] selinux
    - molecule test -d podman
  tags:
    - shell

cleanup_job:
  stage: cleanup
  script:
    - echo "Cleaning up"
    - rm -rf "%CACHE_PATH%/%CI_PIPELINE_ID%"
  when: always

