stages:
  - prepare
  - test

build-container:
  stage: prepare
  script:
    - podman build -t sle-bci-ansible -f molecule/Dockerfile . 
  tags:
    - shell

pip install:
  stage: test
  script:
    - python3 -m virtualenv molecule_ansible --python=python3.8 && source molecule_ansible/bin/activate
    - pip install pip install ansible testinfra molecule podman python-vagrant ansible-lint flake8 molecule[lint] molecule[podman] selinux
    - molecule test
  tags:
    - shell
