---
# MAIN ANSIBLE TASK
- import_tasks: tasks/sles.yml
  when: (ansible_os_family == 'Suse' )
  become: yes

- import_tasks: tasks/zabbix_server.yml
  when: (ansible_zabbix_agent__add_hosts_to_server|default(false)|bool == true)
