---
# tasks file for ansible-zabbix-agent
- name: Check nedded variables
  fail:
    msg: "You need to set a value for ansible_zabbix_agent__ServerAddr"
  when: ansible_zabbix_agent__ServerAddr is undefined

- name: Accept Zabbix GPG Key
  rpm_key:
    state: present
    key: https://repo.zabbix.com/zabbix-official-repo.key

- name: Configure Zabbix Repository on SLES
  zypper:
    name: "https://repo.zabbix.com/zabbix/{{ ansible_zabbix_agent__version }}/sles/{{ ansible_distribution_major_version }}/x86_64/zabbix-release-{{ ansible_zabbix_agent__release }}.sles{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
    update_cache: yes

- name: Install Zabbix Agent
  zypper:
    name: "{{ ansible_zabbix_agent__packages }}"
    state: latest
    update_cache: yes

- name: Remove default agent.d mysql user parameter file
  file:
    name: /etc/zabbix/zabbix_agentd.d/userparameter_mysql.conf
    state: absent

- name: copy zabbix_agentd.conf
  template:
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: root
    group: root
    mode: 0644
  notify: restart_zabbix_agent

- name: Ensure zabbix_agent is set on boot time and start it
  systemd:
    name: zabbix-agent
    enabled: yes
    state: started
